-- PostgreSQL query to create table member

CREATE TABLE public."member" (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	birth_date date NOT NULL,
	email varchar(255) NOT NULL,
	gender varchar(255) NOT NULL,
	ktp_number varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	"password" varchar(255) NOT NULL,
	phone_number varchar(255) NOT NULL,
	photo text NULL,
	"role" varchar(255) NOT NULL,
	CONSTRAINT member_pkey PRIMARY KEY (id),
	CONSTRAINT uklax7dbwxj43e4fc0x9140eppl UNIQUE (ktp_number),
	CONSTRAINT ukmbmcqelty0fbrvxp1q58dn57t UNIQUE (email)
);